project:
  name: qs-workshop
  regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
tests:
  default:
    template: ./templates/master.template.yaml
    regions:
    - us-east-1

    
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      EmailAddress: vjkr@amazon.com
      KeyPairName: ec2kp
      WebserverCIDR: "0.0.0.0/0"
      QSS3KeyPrefix: "qs-workshop/"
      QSS3BucketRegion: "$[taskcat_current_region]"
      QSS3BucketName: "$[taskcat_autobucket]"

